kind: PersistentVolume
apiVersion: v1
metadata:
  name: nfs
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/nfs/kubernetes
    server: 10.10.1.101
                           
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  annotations:
    volume.beta.kubernetes.io/storage-class: "test-nfs"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
