apiVersion: v1
kind: Service
metadata:
  name: front-end
  namespace: udbc
  labels:
    role: front-end
spec:
 selector:
   role: front-end
 ports:
   - port: 8079
     targetPort: 8079
     nodePort: 30006
 type: NodePort
