apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql
  namespace: udbc
  labels:
    app: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: bgops/mysql-db:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: mysql

